import type { NextPage } from 'next';
import Head from 'next/head';
import Introduction from '../components/introduction';

const Home: NextPage = () => {
  return (
    <div className="">
      <Introduction />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
